language: python
install:
  - pip install tox
env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=coverage
script:
  - tox -e $TOXENV
